### ISSUE TITLE
Update asset repo, remove alt font

### ISSUE THREAD

**Issue by caseyahenson** [maximbaz/docker-joypixels-fonts-build#3]
Hi @maximbaz! Just a note that we've released our version 5.0 assets at https://github.com/joypixels/emoji-assets which replaces the emojione-assets repository. We aren't going to publish the _alt files in the repo now either. 

Thanks for everything, this project is 🔥

**Comment by max-baz** [comment]
Thanks for the ping, resuming work on this 🎉 🔥

**Comment by max-baz** [comment]
Done 🎉
